name: links

on: [pull_request]

jobs:

  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Verify internal links
      run: ./hack/verify-links-doc.sh
    - name: Verify internal link anchors
      run: ./hack/verify-link-anchors.sh